### ISSUE TITLE
Self locked?

### ISSUE THREAD

**Issue by pluveto** [Code-Hex/pget#44]
```
C:\vm>pget https://releases.ubuntu.com/20.04.3/ubuntu-20.04.3-live-server-amd64.iso -p 8
[WARNING] Using a large number of connections to 1 URL can lead to DOS attacks.
In most cases, `4` or less is enough. In addition, the case is increasing that if you use multiple connections to 1 URL does not increase the download speed with the spread of CDNs.
See: https://github.com/Code-Hex/pget#disclaimer

Would you execute knowing these?
 (y/n) [n]: y
1.17 GiB / 1.17 GiB [---------------------------------------------------------------------------] 100.00% 54.10 MiB p/s

binding with files...
Error:
  failed to remove "_ubuntu-20.04.3-live-server-amd64.iso.8/ubuntu-20.04.3-live-server-amd64.iso.8.0" in download location: remove _ubuntu-20.04.3-live-server-amd64.iso.8/ubuntu-20.04.3-live-server-amd64.iso.8.0: The process cannot access the file because it is being used by another process.
```
Only running one command.

**Comment by Code-Hex** [comment]
@pluveto Thanks for reporting.
Could you show me what your directory structures (related pget) when it is caused this problem, Thanks,

**Comment by pluveto** [comment]
> @pluveto Thanks for reporting. Could you show me what your directory structures (related pget) when it is caused this problem, Thanks,

It's a just created folder.

```
C:\vm>tree/f
Folder PATH listing
Volume serial number is 6C64-3308
C:.
│   ubuntu-20.04.3-live-server-amd64.iso
│
└───_ubuntu-20.04.3-live-server-amd64.iso.8
        ubuntu-20.04.3-live-server-amd64.iso.8.0
        ubuntu-20.04.3-live-server-amd64.iso.8.1
        ubuntu-20.04.3-live-server-amd64.iso.8.2
        ubuntu-20.04.3-live-server-amd64.iso.8.3
        ubuntu-20.04.3-live-server-amd64.iso.8.4
        ubuntu-20.04.3-live-server-amd64.iso.8.5
        ubuntu-20.04.3-live-server-amd64.iso.8.6
        ubuntu-20.04.3-live-server-amd64.iso.8.7

```

**Comment by 89z** [comment]
Same problem:

~~~
PS D:\Desktop\etc> pget -o before.mp4 -p 9
'https://proxy-034.dc3.dailymotion.com/sec(z1LdIxCmoIMisR-U4IapUZvimeRaVjf0AlUoF7gVx4yGG8_LJpAoY666SeWypm5ljcMGcnGzjhOzRqp9BBAgog)/video/252/572/145275252_mp4_h264_aac_hq_2.mp4'
[WARNING] Using a large number of connections to 1 URL can lead to DOS attacks.
In most cases, `4` or less is enough. In addition, the case is increasing that
if you use multiple connections to 1 URL does not increase the download speed
with the spread of CDNs.
See: https://github.com/Code-Hex/pget#disclaimer

Would you execute knowing these?
 (y/n) [n]: y
1.41 MiB / 117.59 MiB
[>___________________________________________________________117.59 MiB /
117.59 MiB [-----------------------------------] 100.00% 1.46 MiB p/s

binding with files...
Error:
  failed to remove "_before.mp4.9/before.mp4.9.0" in download location: remove
_before.mp4.9/before.mp4.9.0: The process cannot access the file because it is
being used by another process.
~~~

**Comment by bgarvit01** [comment]
Any updates here, facing same issue:
C:\Users\gbgar>pget -p 100 mylink.link(redacted)
[WARNING] Using a large number of connections to 1 URL can lead to DOS attacks.
In most cases, `4` or less is enough. In addition, the case is increasing that if you use multiple connections to 1 URL does not increase the download speed with the spread of CDNs.
See: https://github.com/Code-Hex/pget#disclaimer

Would you execute knowing these?
 (y/n) [n]: y
3.32 GiB / 3.32 GiB [-----------------------------------------------------------------------------------] 100.00% ? p/s

binding with files...
Error:
  failed to remove "_file.100/file.100.0" in download location: remove _file.100/file.100.0: The process cannot access the file because it is being used by another process.

I see file.0 to file.99 in the dowload folder each of 34,763KB
The process had failed many times in between with TLS hadshake error and I resumed manually, but it end it seems like another problem.

@Code-Hex Can we manually bind/combine?

**Comment by Code-Hex** [comment]
Please use v0.2.1 for this issue

I don't have plan to support for this
> Can we manually bind/combine?
